#problem 2 of projecteuler.net

#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.




def recursiveFibonacciCalculator(fibonacciarray, limit, sum)
	newnum = fibonacciarray[0]  + fibonacciarray[1] 
	fibonacciarray[0] = fibonacciarray[1] 
	fibonacciarray[1]  = newnum
	
	if newnum > limit
		return sum
	end
	
	if newnum % 2 == 0
		sum += newnum
	end
	return recursiveFibonacciCalculator(fibonacciarray,limit, sum)
end

fibonacciarray = [1,2]
sum = 2
newnum = 0
limit = 4000000
#limit = 120
puts recursiveFibonacciCalculator(fibonacciarray,limit, sum)


